#!/bin/sh

#--------------------------------------------------------------------------------------
## confFlu - pythonFlu configuration package
## Copyright (C) 2010- Alexey Petrov
## Copyright (C) 2009-2010 Pebble Bed Modular Reactor (Pty) Limited (PBMR)
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
## 
## See http://sourceforge.net/projects/pythonflu
##
## Author : Alexey PETROV
##


#--------------------------------------------------------------------------------------
# This script applies the procedure for preparing  the configure process. 
# It creates configuration files (ex: ltmain.sh) using libtoolize, 
# the aclocal macro, the configure script using autoconf and some scripts
# used in building process (ex: install-sh) using automake. 


#--------------------------------------------------------------------------------------
confflu_dir=${0%/*}; 
#echo \${confflu_dir} = "${confflu_dir}"

other_includes=$*
#echo \${other_includes} = "${other_includes}"


echo "---------------------------------- aclocal --------------------------------------"
# aclocal creates the aclocal.m4 file from the standard macro and the
# custom macro embedded in the directory ./admin.
# output:
#   aclocal.m4
#   autom4te.cache (directory)

aclocal ${other_includes} -I ${confflu_dir}/admin -I admin || exit 1


echo "--------------------------------- libtoolize ------------------------------------"
# libtoolize creates some configuration files (ltmain.sh,
# config.guess and config.sub). It only depends on the libtool
# version. The files are created in the directory specified with the
# AC_CONFIG_AUX_DIR(<mydir>) tag (see configure.ac).
# output:
#   ./admin/config.guess
#   ./admin/config.sub
#   ./admin/ltmain.sh

case `uname -s` in
Darwin) # use the libtools from MacPorts
   glibtoolize --force --copy --automake || exit 1
   ;;
*)
   libtoolize --force --copy --automake || exit 1
   ;;
esac


echo "---------------------------------- autoconf -------------------------------------"
# autoconf creates the configure script from the file configure.ac (or
# configure.in if configure.ac doesn't exist)
# output:
#   configure

autoconf || exit 1


echo "---------------------------------- automake -------------------------------------"
# automake creates some scripts used in building process
# (install-sh, missing, ...). It only depends on the automake
# version. The files are created in the directory specified with the
# AC_CONFIG_AUX_DIR(<mydir>) tag (see configure.ac). This step also
# creates the Makefile.in files from the Makefile.am files.
# output:
#   ./admin/compile
#   ./admin/depcomp
#   ./admin/install-sh
#   ./admin/missing
#   ./admin/py-compile
#   Makefile.in (from Makefile.am)

# Add possibility to fail for missing Makefile.am
automake --add-missing --copy --gnu 1>&2 2>/dev/null


echo "------------------------------------ OK -----------------------------------------"
